# Generated by Django 4.1.2 on 2022-11-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
